// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq05e_t92wUK9c7XF4aTjiMX4IsLnAG00',
    appId: '1:1030137661647:web:5d11fbc436171b7bbd0fba',
    messagingSenderId: '1030137661647',
    projectId: 'mediashare-cd7fc',
    authDomain: 'mediashare-cd7fc.firebaseapp.com',
    storageBucket: 'mediashare-cd7fc.appspot.com',
    measurementId: 'G-KNGLEWQGCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cOS17xqZyXUllTQbm42te1K98S51kjo',
    appId: '1:1030137661647:android:ab2ee0e5cc50da31bd0fba',
    messagingSenderId: '1030137661647',
    projectId: 'mediashare-cd7fc',
    storageBucket: 'mediashare-cd7fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzu0fND-WMdfrxSWKsfulrQD1ALHXzGtU',
    appId: '1:1030137661647:ios:fa49063d6431dc87bd0fba',
    messagingSenderId: '1030137661647',
    projectId: 'mediashare-cd7fc',
    storageBucket: 'mediashare-cd7fc.appspot.com',
    iosBundleId: 'com.example.mediaShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzu0fND-WMdfrxSWKsfulrQD1ALHXzGtU',
    appId: '1:1030137661647:ios:bb5cbf86996c62b2bd0fba',
    messagingSenderId: '1030137661647',
    projectId: 'mediashare-cd7fc',
    storageBucket: 'mediashare-cd7fc.appspot.com',
    iosBundleId: 'com.example.mediaShare.RunnerTests',
  );
}
